version: '3'

services:

  nginx:
    container_name: hakaton_nginx
    build: ./nginx
    ports:
      - 8000:80
    depends_on: 
      - web
    volumes: 
      - static_volume:/home/app/web/staticfiles

  db:
    container_name: hakaton_postgres
    image: postgres:13.0
    volumes: 
      - pg_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_db=postgres

  redis:
    container_name: hakaton_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data/
    restart: always

  web:
    container_name: hakaton_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes: 
      - static_volume:/home/app/web/staticfiles
    expose: 
      - 8000
    env_file:
      - ./.env
    depends_on: 
      - db
      - redis

volumes: 
  pg_data:
  static_volume:
  redis_data: